name: CI/CD

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: install pnpm
        run: npm install -g pnpm

      - name: build project
        run: pnpm --filter @apps/element-admin build
